### ISSUE TITLE
Load the data simultaneously

### ISSUE THREAD

**Issue by carolineolivia** [prolike/prolike.io#484]
The data needs to load simultaneously. (I can't remember if we already did this?)
@Alfen321 Will this work if we remove `"use strict";`? Please estimate :)

**Comment by Alfen321** [comment]
`"use strict";` Has nothing to do with running things simultaneously, it's only to enforce good coding styles like syntax, declaring variables before use, error out on bad behavior like deleting functions.

This is only done for the page that shows all the boards. But still needs to be made for all the other places we are requesting from different api's.

Load the data simultaneously would be to rewrite some of the js like we did [here](https://github.com/prolike/prolike.io/blob/master/js/getBoard.js) in issue #475

To ensure we can see the page (not getting blank page loading) before we start calling the api's
we did [this](https://github.com/prolike/prolike.io/blob/master/js/getBoard.js#L3)

To make it do "stuff" simultaneously is the [onload](https://github.com/prolike/prolike.io/blob/master/js/getBoard.js#L11) which means call this function on the return of REST content.

We just need to make sure the behavior is intentional and not end up with race conditions (try to use the returned REST content before it has been return).

This is not something to estimate as the problem or solution doesn't have a scope (which pages) or do you mean the individual board?

**Comment by carolineolivia** [comment]
@Alfen321 
Okay, it all makes sense to me, so we doesn't need an indivdual specific issue about this, as it is just some precautions we need to take while making the request, am i right? 😄

**Comment by lakruzz** [comment]
Im closing this, for now, as the load simultaneously issue is more of a thing to create a nice looking interface (can't have a web site doing _nothing_ for several seconds. 

We will reintroduce this issue when we need it
